/**
 * BMAD Agent Definitions — Copilot SDK Custom Agents
 *
 * Each BMAD role is defined as a Copilot SDK customAgent with the authentic
 * BMAD V6 persona prompts, activation instructions, and skill references.
 *
 * Auto-generated by scripts/convert-bmad-agents.ts — do not edit manually.
 * Source: bmad_res/bmm/agents/ (BMAD Method V6)
 */

export { bmadAnalyst } from "./analyst.js";
export { bmadArchitect } from "./architect.js";
export { bmadDev } from "./developer.js";
export { bmadPm } from "./product-manager.js";
export { bmadQa } from "./qa-engineer.js";
export { bmadQuickFlowSoloDev } from "./quick-flow-solo-dev.js";
export { bmadSm } from "./scrum-master.js";
export { bmadTechWriter } from "./tech-writer.js";
export { bmadUxDesigner } from "./ux-designer.js";

export type BmadAgentName =
  | "bmad-analyst"
  | "bmad-architect"
  | "bmad-dev"
  | "bmad-pm"
  | "bmad-qa"
  | "bmad-quick-flow-solo-dev"
  | "bmad-sm"
  | "bmad-tech-writer"
  | "bmad-ux-designer";

/**
 * Registry of all BMAD agents for use in session creation.
 */
export { allAgents, getAgent } from "./registry.js";
