import type { BmadAgent } from "./types.js";
import { bmadAnalyst } from "./analyst.js";
import { bmadArchitect } from "./architect.js";
import { bmadDev } from "./developer.js";
import { bmadPm } from "./product-manager.js";
import { bmadQa } from "./qa-engineer.js";
import { bmadQuickFlowSoloDev } from "./quick-flow-solo-dev.js";
import { bmadSm } from "./scrum-master.js";
import { bmadTechWriter } from "./tech-writer.js";
import { bmadUxDesigner } from "./ux-designer.js";

/**
 * All BMAD agents, ready to pass to CopilotClient.createSession({ customAgents }).
 *
 * Auto-generated by scripts/convert-bmad-agents.ts — do not edit manually.
 */
export const allAgents: BmadAgent[] = [
  bmadAnalyst,
  bmadArchitect,
  bmadDev,
  bmadPm,
  bmadQa,
  bmadQuickFlowSoloDev,
  bmadSm,
  bmadTechWriter,
  bmadUxDesigner,
];

/**
 * Lookup agent by name (canonical ID like "bmad-pm", "bmad-dev", etc.)
 */
export function getAgent(name: string): BmadAgent | undefined {
  return allAgents.find((a) => a.name === name);
}
